### PR TITLE
feat: provide schema for config based on tauri-build version

### PR DESCRIPTION
**Pull request by amrbashir**
This PR also includes:
- changed release CI to use `repository-dispatch` to match the workflow in our other repos like tauri and create-tauri-app
- prettier formatting of the project

### CODE REVIEW

**Comment by FabianLars** [comment]
The problem here is that the cli doesn't really care about the config anymore, it's all handled by tauri-build now and the cli only forwards configs added via the `--config` flag.
In other words, if the user updates the cli or tauri-build without updating the other one it will pull the wrong schema file.

Aaand in a new CTA project i get this error: `Unable to load schema from 'tauri://schemas/config.json': cannot open tauri://schemas/config.json. Detail: Unable to resolve resource tauri://schemas/config.json. (768)`

**Comment by amrbashir** [comment]
> The problem here is that the cli doesn't really care about the config anymore, it's all handled by tauri-build now and the cli only forwards configs added via the `--config` flag.
> In other words, if the user updates the cli or tauri-build without updating the other one it will pull the wrong schema file.

So I should check tauri-build version? cause that would be easier.

> Aaand in a new CTA project i get this error: `Unable to load schema from 'tauri://schemas/config.json': cannot open tauri://schemas/config.json. Detail: Unable to resolve resource tauri://schemas/config.json. (768)`

I just realized I have most  of the code for this PR commented out LOL plus the fallback to latest version won't work until tauri's new release.

**Comment by FabianLars** [comment]
> So I should check tauri-build version? cause that would be easier.

As i understand it, yes

**Review by FabianLars — APPROVED** [review]
LGTM. Not too much of a javascript guy, but couldn't spot anything. Anywayyy, i tested the extension in multiple projects (my own and random community projects) with both default and more complicated structures. Everything seems to work.

**Comment by amrbashir** [comment]
Thanks, merging...

**Pull request merged**
